# -*- coding: utf-8 -*-
{
    "name": "Product Connect Module",
    "version": "17.0.1.3",
    "category": "Industries",
    "author": "Chris Busillo",
    "company": "Shiny Computers",
    "website": "https://www.shinycomputers.com",
    "depends": [
        "base",
        "product",
        "web",
        "website_sale",
        "base_automation",
        "stock",
        "mail",
    ],
    "description": "Module to scrape websites for model data.",
    "data": [
        "data/res_config_data.xml",
        "security/ir.model.access.csv",
        "views/printnode_interface_views.xml",
        "views/product_import_views.xml",
        "views/product_import_wizard.xml",
        "views/product_product_views.xml",
        "views/product_template_views.xml",
        "views/product_manufacturer_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "product_connect/static/src/css/search_mpn_online_widget.css",
            "product_connect/static/src/js/search_mpn_online_widget.js",
            "product_connect/static/src/xml/search_mpn_online_widget.xml",
            "product_connect/static/src/css/file_drop_widget.css",
            "product_connect/static/src/js/file_drop_widget.js",
            "product_connect/static/src/xml/file_drop_widget.xml",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
